Repository CMPUT301F22T15/Foodverse, pull requests merged in 2022-11, with the labels that each got.

#57 Adding updated UI Mockups. #54
  doc/ui_mockups/IngredientList.PNG
  doc/ui_mockups/MealPlan.PNG
  doc/ui_mockups/NavigationPaths.PNG
  doc/ui_mockups/RecipeList.PNG
  doc/ui_mockups/Shopping List.PNG
Labels: documentation, Urgent, Part 3

#60 Added a meaningful test for ShoppingList.
  app/src/androidTest/java/com/example/foodverse/MealPlanActivityTest.java
  app/src/androidTest/java/com/example/foodverse/ShoppingListActivityTest.java
Labels: enhancement, Urgent, Part 3

#72 Issue #3 Implemented ability to pick up ingredients on the shopping list
  app/src/main/java/com/example/foodverse/ShoppingList.java
  app/src/main/java/com/example/foodverse/ShoppingListActivity.java
  app/src/main/java/com/example/foodverse/ShoppingListFragment.java
  app/src/main/java/com/example/foodverse/ShoppingListIngredient.java
  app/src/main/res/layout/activity_shopping_list.xml
  app/src/main/res/layout/shopping_list_fragment.xml
  app/src/main/res/layout/shopping_list_item.xml
Labels: enhancement

#80 Merge in Login Functionality
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/example/foodverse/CategoryList.java
  app/src/main/java/com/example/foodverse/LocationList.java
  app/src/main/java/com/example/foodverse/LoginActivity.java
  app/src/main/java/com/example/foodverse/MealPlanActivity.java
  app/src/main/java/com/example/foodverse/RecipeActivity.java
  app/src/main/java/com/example/foodverse/RecipeFragment.java
  app/src/main/java/com/example/foodverse/ShoppingListActivity.java
  app/src/main/java/com/example/foodverse/StoredIngredientActivity.java
  app/src/main/java/com/example/foodverse/StoredIngredientFragment.java
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/login_bg.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/menu/nav_menu_options.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/strings.xml
Labels: enhancement

#81 Added null value checks to shopping list to stop crashes.
  app/src/main/java/com/example/foodverse/ShoppingListActivity.java
Labels: bug

#82 Ensured OwnerUID is always set.
  app/src/main/java/com/example/foodverse/MealPlanActivity.java
  app/src/main/java/com/example/foodverse/RecipeActivity.java
  app/src/main/java/com/example/foodverse/ShoppingListActivity.java
  app/src/main/java/com/example/foodverse/StoredIngredientActivity.java
Labels: bug, enhancement

#83 Fixed Firebase queries for user specific data.
  app/src/main/java/com/example/foodverse/CategoryList.java
  app/src/main/java/com/example/foodverse/LocationList.java
  app/src/main/java/com/example/foodverse/LoginActivity.java
  app/src/main/java/com/example/foodverse/MealPlanActivity.java
  app/src/main/java/com/example/foodverse/RecipeActivity.java
  app/src/main/java/com/example/foodverse/ShoppingListActivity.java
  app/src/main/java/com/example/foodverse/StoredIngredient.java
  app/src/main/java/com/example/foodverse/StoredIngredientActivity.java
  app/src/main/java/com/example/foodverse/StoredIngredientFragment.java
  app/src/test/java/com/example/foodverse/StoredIngredientTests.java
Labels: bug, enhancement

#85 Fixed firebase issues in ShoppingList.
  app/src/main/java/com/example/foodverse/ShoppingListActivity.java
  app/src/main/java/com/example/foodverse/ShoppingListFragment.java
Labels: bug, enhancement

#88 Fixed sorting issues in Firebase
  app/src/main/java/com/example/foodverse/RecipeActivity.java
  app/src/main/java/com/example/foodverse/ShoppingListActivity.java
  app/src/main/java/com/example/foodverse/ShoppingListFragment.java
  app/src/main/java/com/example/foodverse/StoredIngredientActivity.java
  app/src/main/res/layout/shopping_list_fragment.xml
Labels: bug, enhancement

#91 Ensured categories were fetched for meal ingredients.
  app/src/main/java/com/example/foodverse/MealPlanActivity.java
  app/src/main/java/com/example/foodverse/RecipeActivity.java
Labels: bug, enhancement
